src/components/Column/index.js, src/components/Grid/index.js, src/components/Theme/theme.js, src/pages/about.js, src/pages/careers.js
=> About fixes

src/pages/technology/contribute.js
=> :bug: fix bounty pluralize & add full bounty amount

package.json, src/components/GDPR/index.js, src/components/Layout/index.js, src/components/Theme/index.js, src/components/Theme/theme.js, src/helpers/richTextRenderer.js, yarn.lock
=> Gdpr popup

src/pages/technology/contribute.js
=> Fix null open bounties

package-lock.json, package.json, src/components/Navigation/index.js
=> Fixed mobile nav responsive issue

gatsby-config.js, lambda/getMediumPosts.js, src/components/News/index.js, src/pages/news.js
=> Medium Article Tweaks

lambda/getMediumPosts.js
@lucasvo revert my commit from develop and then merge this, so that the lambda functions get added first
=> feat: add lambda for getting latest medium posts

src/components/News/index.js, src/pages/news.js
=> Remove press block

src/components/News/index.js, src/pages/index.js
=> feat: add latest news section on homepage

src/pages/invest.md, src/pages/products/tinlake/index.md
added "open tinlake" button to `/products/tinlake` page
=> fix: fix typos and add tinlake button on tinlake page

src/pages/products/tinlake/index.md
=> FAQ button on tinlake page

src/pages/products/tinlake/index.md
=> fix: sections misaligned in tinlake page

src/components/EmailSubscription/index.js, src/components/FAQ/index.js, src/components/Footer/footerItem.js, src/components/Footer/index.js, src/components/Theme/theme.js, src/pages/finance.md, src/pages/invest.md, src/pages/products/tinlake/index.md, src/partials/home/BorrowerContactForm.js, src/partials/home/InvestorContactForm.js
=> fix: UI updates, update emails

lambda/getTotalIssuance.js
This pull request adds a `getTotalIssuance` lambda per CoinGecko's request. The api would be queried like so:
```
GET: https://centrifuge.io/.netlify/functions/getTotalIssuance
returns string
```
=> feat: add totalIssuance lambda

src/components/Auction/Crowdloan.js
This pull request extends the early bird deadline by another 24 hours.
=> extend early bird deadline

src/components/AltairHero/index.js, src/components/Auction/Crowdloan.js, src/components/Auction/Header.js, src/components/Auction/HeaderPill.js, src/components/Auction/Prerequisites.js, src/components/Auction/Stake.js, src/components/JoinAltairCommunity/index.js
This pull request includes: 
- Header pill that shows total KSM raised :white_check_mark:
- Refactored surprise bonus card to be more clear :white_check_mark:
- Update the text on the prerequisite list :white_check_mark:
- Added explainer for users who did not authorize the extension :white_check_mark:
- Added FAQ :white_check_mark:
- Updated button text on /altair page to read as Join the Crowdloan :white_check_mark:
=> make UI tweaks

src/components/Auction/Stake.js
This pull request reduces the size of the referral code memo.
=> fix: referral code size

src/components/Auction/BonusCard.js, src/components/Auction/Crowdloan.js
This pull request updates the heavyweight card.
[Preview Link](https://staging.web.cntrfg.com/altair/crowdloan)
=> chore: update heavyweight card

lambda/sendEmail.js, src/partials/issuers/IssuersForm.js
Issue: [326](https://github.com/centrifuge/website/issues/326)
see: [spam filters docs](https://docs.netlify.com/forms/spam-filters/)
=> feat: add netlify spam filter (326)

src/components/Auction/Crowdloan.js, src/components/Auction/Header.js, src/components/Auction/Stake.js, src/pages/altair/crowdloan.md
This pull request:
- new top heavyweight bonus card
- disabled inputs
- update banner
[Preview Link](https://staging.web.cntrfg.com/altair/crowdloan)
=> chore: add new rewards and disable inputs

src/components/Auction/Crowdloan.js, src/components/EmailSubscription/index.js, src/components/Footer/footerItem.js, src/components/Navigation/index.js, src/components/Team/index.js, src/pages/news.js, src/partials/home/LatestNewsSection.js, src/partials/issuers/WhyCentrifuge.js
- Added missing href to the "Join the community" button
- Removed stale code
=> Join community button

src/components/Auction/SwapAddress.tsx
This pull request fixes the way status code responses are handled.
=> fix: status code logic

src/components/Auction/SwapAddress.tsx
This pull request releases the changes from #383.
=> release: status code fix

lambda/getTopContributors.js, src/components/ParachainCrowdloan/Content/Content.tsx, src/components/ParachainCrowdloan/Content/RewardsBreakdown.tsx, src/components/ParachainCrowdloan/shared/format.ts
This pull request fixes the encoding type for encoding Polkadot addresses.
=> fix: encoding type

src/components/ParachainCrowdloan/Hero/AuctionEnded.tsx, src/components/ParachainCrowdloan/shared/config.ts
=> chore: release crowdloan win page

src/components/CrossPageBanner/index.tsx, src/components/ParachainCrowdloan/Content/Content.tsx, src/components/ParachainCrowdloan/Content/InfoBoxList.tsx, src/components/Polkadot/PolkadotHero.js
- Remove "contribute with parallel" link from parachain page
- Change blue banner wording
- Change "join crowdloan" button in "check rewards"
- Show early bird banner
=> Release: reflect changes after winning

lambda/getCentrifugeRewardData.js, src/components/ParachainCrowdloan/Content/RewardsBreakdown.tsx
This pull request adds support for individuals who claimed to the Centrifuge crowdloan through outside channels to claim their rewards.
=> feat: add logic for additonal cont

lambda/getCentrifugeRewardData.js, src/components/ParachainCrowdloan/Content/RewardsBreakdown.tsx
This pull request releases the refactor of the crowdloan claim page to just show the total amount from the merkle tree.
=> release: reward totals fix

src/components/header/index.tsx, src/components/header/styles.tsx, src/hooks/use-scroll-direction.tsx
Ticket
https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/centrifuge/website/476
=> Hide/Show Header based on scroll direction

src/components/work-principle/styles.tsx
- sets maxHeight img
- tweaks maxWidth img
=> design tweak

data/privacy.json, gatsby-ssr.tsx, src/components/ContributorsSection.tsx, src/components/GlobalStyle.tsx, src/components/PrivacySection.tsx, src/pages/privacy.tsx, src/theme.ts
#501 
Also fixes font loading in development
=> Privacy page

README.md, lambda/esbuild.js, lambda/routes.json, lambda/src/getLeverPositions.ts, src/hooks/use-lever-positions.tsx
removing unused empty options object -> moves it to readme
Ticket: https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/centrifuge/website/498
=> fetching vacancies from lever

data/contributors.json, lambda/src/getLeverPositions.ts, src/components/career-section/index.tsx, src/components/career-section/styles.tsx, src/hooks/use-lever-positions.tsx, src/pages/contributors.tsx
Ticket: https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/centrifuge/website/595
=> CareerSection

src/components/contributors-section/Contributor.tsx, src/components/contributors-section/DesktopCarousel.tsx, src/components/contributors-section/index.tsx, src/components/contributors-section/styles.tsx
- refactor to one carousel
- sets custom maxWidth
- fade out left/right if screen is wider then maxWidth
=> Refactor DesktopCarousel

src/components/hero-main/index.tsx, src/components/hero-main/styles.tsx
- max height on hero root element
- window height related width for graphic
=> Hero refactor dimensions

config/footer.ts, src/components/NewsSection.tsx
- updates careers link
- fix ios returning Invalid Date
=> careers link + invalid date

src/components/NewsSection.tsx
https://reactjs.org/docs/error-decoder.html?invariant=423
- render if loading is false
=> Minified react error

.github/workflows/cleanup-pr.yml
This PR will be merged by author to test the cleanup PR (only trigger when PR closes)
=> Fix Cleanup PR job

data/home.json, src/components/PrimeBanner.tsx, src/pages/index.tsx
- in production deploy json data was missing and the component rendered without content
=> replace content into component

config/links.ts, src/components/RwaUsp.tsx, src/components/text-image/index.tsx
- extends TextImage with optional titleAddition slot
=> Link to Prime blog post

data/about.json, data/legal/security.md, data/posts/posts.json
Updates news and fixes a link on security page.
=> Update news and fix link in /security

data/home.json, src/components/Image.tsx, src/components/partner-list/index.tsx
=> Add polkadot to partners list
